title: Intermediate Python
author: Nick Ulle
copyright: "2025"
logo: img/datalab-logo-full-color-rgb-1.png
exclude_patterns: [_build, .pixi]
only_build_toc_files: true

repository:
  url: https://github.com/ucdavisdatalab/workshop_intermediate_python

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

execute:
  execute_notebooks: auto

html:
  use_issues_button: true
  use_repository_button: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
